### ISSUE TITLE
flow-db-admin wont install

### ISSUE THREAD

**Issue by danishfred** [sachinbhutani/flow-db-admin#44]
flow-db-admin looks very interesting but several try on installation all end up with
"TypeError: Cannot read property 'constructor' of undefined
W20190809-12:17:25.436(2)? (STDERR)     at exposeSubscription (packages\meteorhacks_meteorx.js:69:41)
W20190809-12:17:25.437(2)? (STDERR)     at exposeLivedata (packages\meteorhacks_meteorx.js:39:5)
W20190809-12:17:25.437(2)? (STDERR)     at packages\meteorhacks_meteorx.js:130:1
W20190809-12:17:25.439(2)? (STDERR)     at packages\meteorhacks_meteorx.js:135:4
W20190809-12:17:25.439(2)? (STDERR)     at packages\meteorhacks_meteorx.js:139:4
W20190809-12:17:25.586(2)? (STDERR)     at packages\meteorhacks_meteorx.js:147:3
W20190809-12:17:25.587(2)? (STDERR)     at C:\METEOR\sandbox\admin1\.meteor\local\build\programs\server\boot.js:419:36
W20190809-12:17:25.587(2)? (STDERR)     at Array.forEach (<anonymous>)
W20190809-12:17:25.588(2)? (STDERR)     at C:\METEOR\sandbox\admin1\.meteor\local\build\programs\server\boot.js:228:19
W20190809-12:17:25.588(2)? (STDERR)     at C:\METEOR\sandbox\admin1\.meteor\local\build\programs\server\boot.js:479:5"

I'm tying to install in a quite untouched new project, so no third party interruptions.
Any suggestions ???

**Comment by sachinbhutani** [comment]
sorry, i am no longer able to maintain this repo.
